### ISSUE TITLE
[BUG] CentOS 7.x find 4.5.11 has a fd leak in -execdir - Too many open files

### ISSUE THREAD

**Issue by Techcadia** [sous-chefs/selinux_policy#88] opened 2018-11-15 20:07 UTC
### Cookbook Version
 2.0.1+
### Chef-client version 
12.x -> 14.x
### Platform Details
CentOS 7.x Current

### Scenario:

find (GNU findutils) 4.5.11 has a filedescriptor leak in -execdir. This has been patched in 4.5.12 (http://git.savannah.gnu.org/cgit/findutils.git/commit/?id=183115d0) but currently CentOS 7.x runs on 4.5.11 (https://pkgs.org/download/findutils). 

This change is what created this bug.
https://github.com/sous-chefs/selinux_policy/pull/67/commits/4c574249527a26cda63a6b795750f00a1a2b61ba

### Steps to Reproduce:
Step to repo can be found at the bottom of this post.
http://git.savannah.gnu.org/cgit/findutils.git/commit/?id=183115d0

Easiest way to repo is create a bunch of folders and files and then run on centOS 7.x while lowering ulimits.

```ulimits -n 256; chef-client```

### Expected Result:
restorecon works

### Actual Result:
```
[2018-11-15T18:02:22+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-11-15T18:02:22+00:00] ERROR: selinux_policy_fcontext[/var/lib/kafka(/.*)?] (cf_kafka::_config line 66) had an error: Mixlib::ShellOut::ShellCommandFailed: selinux_policy_fcontext[/var/lib/kafka(/.*)?] (cf_kafka::_config line 66) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of ["find", "/", "-regextype", "posix-egrep", "-regex", "/var/lib/kafka(/.*)?", "-execdir", "restorecon", "-iRv", "{}", ";"] ----
STDOUT:
STDERR: find: Failed to save working directory in order to run a command on ‘00000000000000890135.log’: Too many open files
---- End output of ["find", "/", "-regextype", "posix-egrep", "-regex", "/var/lib/kafka(/.*)?", "-execdir", "restorecon", "-iRv", "{}", ";"] ----
Ran ["find", "/", "-regextype", "posix-egrep", "-regex", "/var/lib/kafka(/.*)?", "-execdir", "restorecon", "-iRv", "{}", ";"] returned 1
[2018-11-15T18:02:22+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by josephholsten** [comment] 2018-11-19 20:45
@Techcadia how should we go about fixing this?

**Comment by Techcadia** [comment] 2018-11-19 20:48
That's a great question @josephholsten. My first thought is revert back to using find + xargs vs inline. @daften might have a better understanding on why it was moved to `-execdir` as he was the one to commit the change. Seen here https://github.com/sous-chefs/selinux_policy/pull/67/commits/4c574249527a26cda63a6b795750f00a1a2b61ba

**Comment by damacus** [comment] 2018-11-21 18:12
If you can get it working on find+args, then I say revert. Until we find a bug with that. 

Fancy throwing a PR together?

**Comment by daften** [comment] 2018-12-17 12:45
> That's a great question @josephholsten. My first thought is revert back to using find + xargs. @daften might have a better understanding on why it was moved to `-execdir` as he was the one to commit the change. Seen here [4c57424](https://github.com/sous-chefs/selinux_policy/commit/4c574249527a26cda63a6b795750f00a1a2b61ba)

This was done because the first method of using restorecon directly made the scope of the restorecon too big sometimes. See https://github.com/sous-chefs/selinux_policy/issues/56 for more info.

Why -execdir was used, see https://github.com/sous-chefs/selinux_policy/pull/67#discussion_r111671225

**Comment by Techcadia** [comment] 2018-12-19 18:23
@daften can you provide a example of the scope getting to large.

**Comment by daften** [comment] 2018-12-19 18:38
I think I gave an example in the original issue I linked :)

**Comment by Techcadia** [comment] 2018-12-19 18:45
@daften so your saying if we revert it back in PR #91 it will blow up on an edge case I don't see noted anywhere? I have read through the tickets linked twice and don't see where it was mentioned.

**Comment by daften** [comment] 2019-01-09 09:13
Thank you for that polite and definitely not attacking reply...
In the second line in ticket #56 I gave the case:  /var/lib/mysql-default(/.*)?  I use the mysql cookbook, therefore the -default suffix. The problem is with the original way of working it would do a restorecon on /var/lib, which is huge.

**Comment by TechIsCool** [comment] 2019-01-09 17:08
@daften can you run this diff for me.

```
diff \
<(find / -ignore_readdir_race -regextype posix-egrep -regex "/var/lib/mysql-default(/.*)?" -prune -execdir echo {} +) \
<(find / -ignore_readdir_race -regextype posix-egrep -regex "/var/lib/mysql-default(/.*)?" -prune -print0 2>/dev/null | xargs -0 -I {} echo {})
```

Here is what I see returned
```
1c1
< ./mysql-default
---
> /var/lib/mysql-default
```

**Comment by damacus** [comment] 2019-01-10 14:04
Hey guys is there some way we cna move this bug forward?

I'm not seeing any concrete plans right now. If we have something I'm happy to get some consensus and get a fix merged in.

**Closed** 2019-02-06 09:21 UTC
